apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      tolerations:
        {{- range .Values.tolerations }}
        - key: "{{ .key }}"
          operator: "{{ .operator }}"
          value: "{{ .value }}"
          effect: "{{ .effect }}"
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: {{ .Values.imageSecret}}
