replicaCount: 5

image:
  tag: latest

service:
  port: 80
  nodePort: 30010 # Custom NodePort within the range 30000–32767

tolerations:
  - key: "node"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

imageSecret: "dockerhub-image-pull-secret"